name: "publish release"

on:
  push:
    branches:
      - add-trace-viewer-deployment

jobs:
  publish-trace-viewer:
    name: "publish Trace Viewer to trace.playwright.dev"
    runs-on: ubuntu-20.04
    if: github.repository == 'microsoft/playwright'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm i -g npm@7
    - run: npm ci
    - run: npm run build
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: microsoft/playwright-trace
        path: playwright-trace
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        repository: playwright-trace